### ISSUE TITLE
TrajectoryDriveCommand "reversed" probably isn't quite right

### ISSUE THREAD

**Issue by Kevin-OConnor** [FRCTeam238/2024-Robot#2]
The current implementation takes "reversed" as a command parameter meaning that it would have to be passed in from the auto downloader I believe. The reversed here has different meaning than when we were tank drive. We should just pass a lambda to the ChoreoSwerveCommand that uses the alliance color to decide whether to flip it. The command won't use that supplier until it's actually running so alliance should be valid data by then.

**Comment by me6262** [comment]
oh that makes more sense than the little lambda i had that just returned the variable

**Comment by me6262** [comment]
it should be a real quick fix
